export default {
  ADD_ALERT: 'ADD_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  SET_MULTI_PROFILES: 'SET_MULTI_PROFILES',
  SET_PROFILE_ERROR: 'SET_PROFILE_ERROR',
  CLEAR_PROFILE: 'CLEAR_PROFILE'
}